### ISSUE TITLE
GotoDefinition from external Libraries

### ISSUE THREAD

**Issue by tilupe** [Hoffs/omnisharp-extended-lsp.nvim#13]
This is not a real issue since it it not the problem of your plugin, but I wanted to know if it is only me who has that problem, that I am not able to go to external libraries. 
I always get the error:

Error executing vim.schedule lua callback: ...t_nvimWvgMgH/usr/share/nvim/runtime/lua/vim/lsp/util.lua:997: Cursor
 position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...t_nvimWvgMgH/usr/share/nvim/runtime/lua/vim/lsp/util.lua:997: in function 'jump_to_location'
        ...imWvgMgH/usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:343: in function 'handler'
        ....mount_nvimWvgMgH/usr/share/nvim/runtime/lua/vim/lsp.lua:1025: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

I guess somehow it doesn't find the correct way since it opens afterward a buffer with the correct name. 

If this problem is not only mine, would it be maybe possible to extend this plugin such that this is also possible?

**Comment by Hoffs** [comment]
Hi,

Not really sure, but it sounds like it fails to load the file initially and then tries to jump to non existing file. Do you have decompilation enabled and omnisharp properly configured (though it still should work without decompilation)? 

https://github.com/Hoffs/omnisharp-extended-lsp.nvim#omnisharp-settings

Also you can try enabling lsp debugging `:lua vim.lsp.set_log_level("debug")` and seeing if log has anything interesting (you can see log file with `:lua print(vim.lsp.get_log_path())`.
