### ISSUE TITLE
Error if telescope plugin is not installed

### ISSUE THREAD

**Issue by mwebb387** [Hoffs/omnisharp-extended-lsp.nvim#15]
If telescope is not installed `omnisharp-extented-lsp` causes the following error on initialization:

```omnisharp-extended-lsp.nvim/lua/omnisharp_extended.lua:2: module 'telescope.make_entry' not found```

Can Telescope be checked first as an optional dependency?

**Comment by Hoffs** [comment]
Hi,
I added a check in https://github.com/Hoffs/omnisharp-extended-lsp.nvim/commit/83be0f285afa360ca4a134820381e54b4b7aadd3 , should now work fine even if telescope is not available.

**Comment by mwebb387** [comment]
That was fast! Thanks.

Tested with the update and it works great.
