### ISSUE TITLE
handler function can't handle `require("telescope.builtin").lsp_definitions()`

### ISSUE THREAD

**Issue by shusann01116** [Hoffs/omnisharp-extended-lsp.nvim#24]
Hi,

I'm using [AstroNvim](https://github.com/AstroNvim/AstroNvim).
They provide a lot of default configurations and I found the config set both `vim.lsp.buf.definition()` and `require("telescope.builtin").lsp_definitions()` on the same key bind. The latter mapping is preffered and causing the no cursor  error.

I disabled the `require("telescope.builtin").lsp_definitions()` by override the mapping as a workaround. Is it able to handle the function in the handlers section?
https://github.com/AstroNvim/AstroNvim/blob/377db3f7d6273779533c988dadc07a08e0e43f2e/lua/astronvim/utils/lsp.lua#L355

I'm not familier with customizing neovim configurations and lua itself.

**Comment by Hoffs** [comment]
Hi, if I understand correctly, you would want to add a keybind that executes `require('omnisharp_extended').telescope_lsp_definitions()`. So for example:

```
nnoremap gd <cmd>lua require('omnisharp_extended').telescope_lsp_definitions()<cr>
```

Or based on your dotfiles, it would be:

```
return {
  n = {
    -- FIXME: Workaround for omnisharp-extended can't handle telescope's api
    -- https://github.com/Hoffs/omnisharp-extended-lsp.nvim/issues/24
    ["gd"] = {
      function() require('omnisharp_extended').telescope_lsp_definitions() end,
      desc = "Show the definition of current symbol",
    },
  },
}
```

**Comment by shusann01116** [comment]
I see, thank you very much for referring to my dotfiles.
This solved my issue!🥳
