### ISSUE TITLE
Cannot find the function in same $metafile$?

### ISSUE THREAD

**Issue by tidaeu** [Hoffs/omnisharp-extended-lsp.nvim#25]
Repo:

- Made dotnet api template (WeatherForecastController)
- gd on line 38 FromDateTime() takes me too the correct $metafile$
- gd on AddDays(index) fails with error.

<img width="1082" alt="Notworking" src="https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/31824678/9d116961-2e85-41ea-a237-f1dd4efab1f6">
<img width="1010" alt="Working" src="https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/31824678/e43e2e87-88df-404f-a648-267012636b42">

It strange to me which functions its able to find and which it cannot. ILogger it cannot find but ApiController can be found. 

Is this because I'm using dotnet 7?  

Config: 

<img width="980" alt="config" src="https://github.com/Hoffs/omnisharp-extended-lsp.nvim/assets/31824678/a5594984-b3b5-46d8-96f1-75a748e91dd7">

**Comment by Hoffs** [comment]
Hi,
Is it specifically loading files in that order or even if you try to open `AddDays` first? I tried to repro this on my machine, also using dotnet sdk 7, but I did not get this error.
Could you include output of `:LspLog` if you are still having this issue?

**Comment by Hoffs** [comment]
closing the issue, if you're still having issues with latest version, please reopen this issue or create a new one
