### ISSUE TITLE
OmniSharp LSP not working in Neovim for .NET Projects 

### ISSUE THREAD

**Issue by ram-xv** [Hoffs/omnisharp-extended-lsp.nvim#29]
### Issue Summary:
I'm experiencing issues getting OmniSharp LSP to work with Neovim for .NET projects. When opening a .NET project and executing the :LspLog command, I see multiple errors and warnings in the log.

### Environment:
OS: `macOS 14.1 `(same error happens in linux ubuntu 22)
Neovim Version: `v0.9.4`
OmniSharp Version: [v1.39.11](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.11) ([omnisharp-osx.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-osx.zip))
Installed dotnet SDKs: `6.0.418`, `8.0.101`
Mono Version: `6.12.0.199`

Neovim init.lua configuration:
``` lua
local pid = vim.fn.getpid()
local omnisharp_bin = "/Users/rampaged/Downloads/omnisharp-osx/run"

local config = {
  handlers = {
    ["textDocument/definition"] = require("omnisharp_extended").handler,
  },
  cmd = { omnisharp_bin, "--languageserver", "--hostPID", tostring(pid) },

  enable_editorconfig_support = true,
  enable_ms_build_load_projects_on_demand = false,
  enable_roslyn_analyzers = false,
  organize_imports_on_format = false,
  enable_import_completion = false,
  sdk_include_prereleases = true,
  analyze_open_documents_only = false,
}

require("lspconfig").omnisharp.setup(config)

```

### Steps to Reproduce:
1. Install omnisharp-roslyn server version [v1.39.11](https://github.com/OmniSharp/omnisharp-roslyn/releases/tag/v1.39.11) ([omnisharp-osx.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-osx.zip))
2. follow [this documentation](https://github.com/Hoffs/omnisharp-extended-lsp.nvim?tab=readme-ov-file#for-neovim-nightly-06-or-later) to configure custom handler from this plugin. 
3. Open a .NET project in Neovim.
4. Execute :LspLog command.
5. Observe the error and warning messages in the log.

### :LspLog Errors in Neovim after opening a dotnet project
```
[START][2024-01-31 23:55:05] LSP logging initiated
[ERROR][2024-01-31 23:55:05] .../vim/lsp/rpc.lua:734	"rpc"	"/Users/ramfattah/Downloads/omnisharp-osx/run"	"stderr"	"﻿"
[WARN][2024-01-31 23:55:07] ...lsp/handlers.lua:537	"OmniSharp.CompositionHostBuilder: It looks like you have Mono installed which contains a MSBuild lower than 17.0.0 which is the minimum supported by the configured .NET Core Sdk.\n Try updating Mono to the latest stable or preview version to enable better .NET Core Sdk support. | "
[ERROR][2024-01-31 23:55:11] ...lsp/handlers.lua:535	'OmniSharp.MSBuild.ProjectLoader: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. | '
[WARN][2024-01-31 23:55:12] ...lsp/handlers.lua:537	"OmniSharp.MSBuild.ProjectManager: Failed to load project file '/Users/ramfattah/Documents/bots/BotBuilder-Samples/samples/csharp_dotnetcore/02.echo-bot/EchoBot.csproj'. | "
[WARN][2024-01-31 23:55:12] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/msbuildprojectdiagnostics, Params = {\n  \"FileName\": \"/Users/ramfattah/Documents/bots/BotBuilder-Samples/samples/csharp_dotnetcore/02.echo-bot/EchoBot.csproj\",\n  \"Warnings\": [],\n  \"Errors\": [\n    {\n      \"LogLevel\": \"Error\",\n      \"FileName\": \"/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets\",\n      \"Text\": \"The reference assemblies for \\\".NETFramework,Version=v6.0\\\" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.\",\n      \"StartLine\": 1232,\n      \"StartColumn\": 5,\n      \"EndLine\": 0,\n      \"EndColumn\": 0\n    }\n  ]\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/msbuildprojectdiagnostics, Params = {\n  \"FileName\": \"/Users/ramfattah/Documents/bots/BotBuilder-Samples/samples/csharp_dotnetcore/02.echo-bot/EchoBot.csproj\",\n  \"Warnings\": [],\n  \"Errors\": [\n    {\n      \"LogLevel\": \"Error\",\n      \"FileName\": \"/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets\",\n      \"Text\": \"The reference assemblies for \\\".NETFramework,Version=v6.0\\\" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.\",\n      \"StartLine\": 1232,\n      \"StartColumn\": 5,\n      \"EndLine\": 0,\n      \"EndColumn\": 0\n    }\n  ]\n}, TraceParent = , TraceState =  }'"
[ERROR][2024-01-31 23:55:12] ...lsp/handlers.lua:535	"OmniSharp.MSBuild.ProjectManager: Attempted to update project that is not loaded: /Users/ramfattah/Documents/bots/BotBuilder-Samples/samples/csharp_dotnetcore/02.echo-bot/EchoBot.csproj | "

```

Note, i'm new to neovim, not sure if i'm doing this correctly.

happy to provide additional information if needed. 
Thanks.

**Comment by ram-xv** [comment]
Let me know if you'd like me to provide additional logging.

**Comment by Hoffs** [comment]
Hi,

This seems like SDK incompatibility issue rather than plugin one.

Have you tried using net6.0 build of omnisharp - https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-osx-x64-net6.0.zip ? And are you on x64 or arm64 system?

https://github.com/OmniSharp/omnisharp-roslyn/issues/2389#issuecomment-1108527022 

From omnisharp readme:

> OmniSharp is built with the [.NET Core SDK](https://dot.net/) on Windows and [Mono](http://www.mono-project.com/) on OSX/Linux. It targets both the net6.0 and net472 target frameworks. The net6.0 build requires a .NET SDK version >=6.0. When using the net472 build on OSX/Linux, Mono version >=6.4.0 is required and must be globally installed on the system.

**Comment by rampaged** [comment]
Hey @Hoffs, Thanks for the quick response.

I downloaded the .net6 ([linux-x64-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-linux-x64-net6.0.zip)) version of omnisharp-rosyln, but it seems it doesn't contain the `run` file. It has bunch of DLLs.

What shall i provide for `omnisharp_bin` path?:
```lua
local pid = vim.fn.getpid()
local omnisharp_bin = ""

local config = {
  handlers = {
    ["textDocument/definition"] = require("omnisharp_extended").handler,
  },
  cmd = { omnisharp_bin, "--languageserver", "--hostPID", tostring(pid) },
}
require("lspconfig").omnisharp.setup(config)

```

**Comment by ram-xv** [comment]
Hey @Hoffs, thanks for the quick response.

I downloaded the .net6 ([omnisharp-linux-x64-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-linux-x64-net6.0.zip)) version of omnisharp-rosyln and changed the `omnisharp_bin` path to this:
```lua
local pid = vim.fn.getpid()
local omnisharp_dll_path = "/home/rampage/Downloads/omnisharp-roslyn-net6/OmniSharp.dll"

local config = {
  handlers = {
    ["textDocument/definition"] = require("omnisharp_extended").handler,
  },
  cmd = { "dotnet", omnisharp_dll_path, "--languageserver", "--hostPID", tostring(pid) },
}
require("lspconfig").omnisharp.setup(config)

```

Now when I open a dotnet project, the LSP doesnt fully work, specially the go to definition. 

For example the C# syntax highlighting and diagnostics works now but other features like `go to definition`, `Hover Documentation`, `Signature Help`, etc doesn't work at all.

Do you have any suggestions how to proceed? My main goal for this `omnisharp-extended-lsp.nvim` plugin is for "go to definition" to work.

Here is the :LspLog
https://drive.google.com/file/d/1q5MFH0NJy7cJG0frXu0yLWD8W2J2CsnR/view?usp=sharing

**Comment by Hoffs** [comment]
> I downloaded the .net6 ([omnisharp-linux-x64-net6.0.zip](https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.11/omnisharp-linux-x64-net6.0.zip)) version of omnisharp-rosyln and changed the `omnisharp_bin` path to this:

There should be a file named just `OmniSharp` that should be made executable first (`chmod +x OmniSharp`) and that should be specified as LSP bin path

**Comment by ram-xv** [comment]
Thanks for the quick response @Hoffs.

The LSP seems to be "half-working" lol.

Syntax highlighting and and diagnostics works now but the main features i'm looking for such as `go to definition`, `Hover symbol details`, `Signature Help` are not working.

I dont think this is an issue with this `Hoffs/omnisharp-extended-lsp.nvim` plugin. I'll open an issue in either "[OmniSharp/omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn)" or "[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp)" for more help.

Thank you so much for help!
