### ISSUE TITLE
Omnisharp not working with LazyVim and bloating the lsp.log file (13GB+ and counting)

### ISSUE THREAD

**Issue by iryan2** [Hoffs/omnisharp-extended-lsp.nvim#34]
My ~/.local/state/nvim/lsp.log is rapidly filling up with garbage. I think, for every keystroke, the following is being added to that file 

<details>
<summary>click here to expand</summary>

```
[START][2024-05-14 08:35:52] LSP logging initiated
[ERROR][2024-05-14 08:35:52] ...lsp/handlers.lua:535	"OmniSharp.Script.ScriptContextProvider: Failed to resolve compilation dependencies - System.NullReferenceException: Object reference not set to an instance of an object.\n   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.<Restore>g__CreateConfigFileArgument|4_1(<>c__DisplayClass4_0&)\n   at Dotnet.Script.DependencyModel.Context.DotnetRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)\n   at Dotnet.Script.DependencyModel.Context.ProfiledRestorer.Restore(ProjectFileInfo projectFileInfo, String[] packageSources)\n   at Dotnet.Script.DependencyModel.Compilation.CompilationDependencyResolver.GetDependencies(String targetDirectory, IEnumerable`1 scriptFiles, Boolean enableScriptNugetReferences, String defaultTargetFramework)\n   at OmniSharp.Script.ScriptContextProvider.CreateScriptContext(ScriptOptions scriptOptions, String[] allCsxFiles, Boolean editorConfigEnabled) in /Users/runner/work/1/s/src/OmniSharp.Script/ScriptContextProvider.cs:line 89 | "
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
[WARN][2024-05-14 08:35:52] ...lsp/handlers.lua:537	"OmniSharp.Extensions.LanguageServer.Server.LspServerOutputFilter: Tried to send request or notification before initialization was completed and will be sent later OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  } | @Request='OutgoingNotification { Method = o#/backgrounddiagnosticstatus, Params = {\n  \"Status\": 0,\n  \"NumberProjects\": 1,\n  \"NumberFilesTotal\": 1,\n  \"NumberFilesRemaining\": 0\n}, TraceParent = , TraceState =  }'"
```

I have removed most of the output because I was hitting the character limit for the create issue form, but have uploaded it in full [here](https://pastebin.com/WwvUQA8K)

</details>

As you can imagine, this adds up quickly, and before long my log file was 13GB in size. One question that occurred to me is - does `Hoffs/omnisharp-extended-lsp.nvim` install `OmniSharp/omnisharp-roslyn` or am I supposed to be doing that manually?

In any case, I haven't been able to get Omnisharp working in neovim. 

Reproduction:
1. Start a fresh LazyVim config
2. Open neovim and run `:LazyExtras`
3. Enable lang-omnisharp
4. Close neovim
5. Open a `.cs` file in neovim
6. Observe that LSP functionality does not work
7. Observe garbage in log file

Thanks in advance for any assistance you're able to provide.

**Comment by Hoffs** [comment]
Hi,

From what I can see, it seems that OmniSharp LSP server is failing to initialize and then diagnostics are still trying to call the server, thus leading to all those log messages. This seems unrelated to this plugin, as it overrides specific handlers, not diagnostics ones. To confirm that, you could modify your config to remove the plugin and also any handler modifications. 

> One question that occurred to me is - does Hoffs/omnisharp-extended-lsp.nvim install OmniSharp/omnisharp-roslyn or am I supposed to be doing that manually?

This plugin does not perform any installation or configuration, it only builds on top of LSP. OmniSharp LSP configuration information can be found here - https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp

**Comment by Hoffs** [comment]
Looking around, I see from logs this has to do with `csx` files which have a bunch of issues related, e.g.:

- https://github.com/dotnet/vscode-csharp/issues/4976#issuecomment-1018745813
> I will close this because without dotnet script init or manually creating omnisharp.json with the following content: [...] nuget references are not supported.

- https://github.com/OmniSharp/omnisharp-roslyn/issues/2405

Based on those, I would suggest trying one of the suggestions from those issues.

**Comment by Hoffs** [comment]
You could also try to create a new dotnet project (`dotnet new console`) and see if issue persists.

**Comment by iryan2** [comment]
Thank you so much for looking into this. In a new dotnet project, go to definition (`telescope_lsp_definitions()`) appears to work after turning on the `lang-omnisharp` feature in `:LazyExtras` with no further configuration. I'll see if I can get references (`telescope_lsp_references()`) to work via custom LazyVim config.

I'll ask about the error flood in `OmniSharp/omnisharp-roslyn` too. Thanks again, really appreciate your help.

**Comment by dirkesquire** [comment]
Please could you share your Lazy Omnisharp config in your Lua config
