### ISSUE TITLE
Omnisharp with multiple solution files

### ISSUE THREAD

**Issue by chekkan** [Hoffs/omnisharp-extended-lsp.nvim#41]
Is repository with multiple solution files supported with this plugin?

How would you let Omnisharp the solution path to load on a particular repository?

**Comment by Hoffs** [comment]
Hi, I don't really understand the second part of the question. As for the first part, I am not entirely sure if omnisharp supports multiple solutions, is there something that is not working?

Moreover, this plugin only builds on top of omnisharp-roslyn LSP and multiple solution support sounds like something that the LSP would be responsible for. If there is something that is not working specifically in relation to "go to definition" (or similar actions), let me know.

**Comment by chekkan** [comment]
Thanks @Hoffs for your reply. I can see that there is [an existing issue](https://github.com/OmniSharp/omnisharp-roslyn/issues/2299) open in the [OmniSharp/omnisharp-roslyn](https://github.com/OmniSharp/omnisharp-roslyn) repository. I think this issue can be closed.
