### ISSUE TITLE
Can this plugin support csharpl_ls

### ISSUE THREAD

**Issue by Decodetalkers** [Hoffs/omnisharp-extended-lsp.nvim#6]
https://github.com/razzmatazz/csharp-language-server
I don't know if csharp_ls can also provide decompile . But it is a better lsp for csharp

**Comment by Decodetalkers** [comment]
csharp-ls uses [ILSpy/ICSharpCode.Decompiler](https://github.com/icsharpcode/ILSpy) to decompile types in assemblies to C# source;

It use this to decompile

**Comment by Hoffs** [comment]
I don't really understand what is the issue, as I see `csharp_ls` already has decompilation support built in and I assume working. So if you want to use csharp_ls as csharp lsp, it should have decompilation working and this plugin is not needed. This plugin is only 
needed to workaround/fix the `$metadata$` issue when working with default roslyn lsp server.

**Comment by Decodetalkers** [comment]
> 

I see ,but it not work.. I will ask them later
