### ISSUE TITLE
Indicate decompilation may require omnisharp.json->EnableDecompilationSupport

### ISSUE THREAD

**Issue by redbeardt** [Hoffs/omnisharp-extended-lsp.nvim#8]
```
Platform: Windows 10
Terminal: Wezterm 20220403-144923-54d503de
Neovim: v0.7.0-dev+1241-g08d9d74fd
```

I tried to use this plugin several times but never managed to view decompiled source, only metadata. I recently discovered the boolean `EnableDecompilationSupport` property in `~/.omnisharp/omnisharp.json` under `RoslynExtensionsOptions`. Upon setting it to `true`, decompilation worked.

My suggestion is that it be indicated in the `README.md` that users may need to set this value in order for decompilation to work. Maybe this is obvious, but it wasn't for me. .__.

Demonstration:

https://user-images.githubusercontent.com/22147604/164874339-cefaafe6-39be-45b4-89e3-41fc89b209ca.mp4

**Comment by Hoffs** [comment]
Hi,

I remember testing it and it seemed to work even when I didn't enable it in omnisharp settings, so maybe thats why I forgot to include it. Nevertheless, updated readme in https://github.com/Hoffs/omnisharp-extended-lsp.nvim/commit/d3fe9f38047fdfb26b85d982be94e78bb42349bb
